# -*- coding: utf-8 -*-
"""HealthCareEDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDq5FKRI05b9zCoO4Jro1pTTQFHnECRn
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import pickle
from google.colab import files

"""**Load the dataset**"""

# 1. Load the dataset
df = pd.read_csv('healthcare.csv')
print("Dataset Loaded Successfully!")
print(df.head())

"""Exploratory Data Analysis (EDA)"""

# 2. Exploratory Data Analysis (EDA)
plt.figure(figsize=(15, 5))
# Plot 1: Medical Conditions Count
plt.subplot(1, 3, 1)
sns.countplot(data=df, x='Medical Condition')
plt.title('Medical Conditions Distribution')
plt.xticks(rotation=45)

# Plot 2: Test Results Count
plt.subplot(1, 3, 2)
sns.countplot(data=df, x='Test Results')
plt.title('Test Results Distribution')

# Plot 3: Medication Count
plt.subplot(1, 3, 3)
sns.countplot(data=df, x='Medication')
plt.title('Medication Used')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('eda_plots.png')
plt.show()

"""**Preprocessing the Data**

**Train the Model**
"""

# 4. Train the Model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Print Accuracy
accuracy = model.score(X_test, y_test)
print(f"Model Accuracy on Test Data: {accuracy * 100:.2f}%")

"""**Export to a .pkl File**"""

#5. Export to a .pkl File
with open('healthcare_model.pkl', 'wb') as file:
    pickle.dump(model, file)

# Download the model to your PC automatically
files.download('healthcare_model.pkl')